import {
  CLEAR_STATE_USER,
  SET_INPUT_USER,
  WAITING_DATA,
  STOP_WAITING_DATA,
  SET_INITIAL_DATA,
  CLEAR_DATA_REPORT,
} from './types';

const initialState = {
  loading: false,
  user: {},
  clients: [],
  brandsCon: [],
  brandsAir: [],
  equipCon: [],
  equipAir: [],
  supervisors: [],
  accesories: [],
  token: '',
  codSofya: '',
  idClienteSelect: 0,
  direccion: '',
  idSupervisorSelect: 0,
  local: '',
  nomCli: '',
  dniCli: '',
  cargoCli: '',
  ubicacion: '',
  fecha: '',
  horInicio: '00:00',
  horFin: '00:00',
  idMarcaAir: 0,
  idTipoAir: 0,
  capacidadAir: '',
  energiaAir: '',
  refrigeranteAir: '',
  idMarcaVen: 0,
  idTipoVen: 0,
  capacidadVen: '',
  energiaVen: '',
  idEquipoGen: 0,
  modeloGen: '',
  serieGen: '',
  idEquipoTwoGen: 0,
  modeloTwoGen: '',
  serieTwoGen: '',
  observaciones: '',
  recomendaciones: '',
  compresor1: '',
  compresor2: '',
  compresor3: '',
  ventiladorCon1: '',
  ventiladorCon2: '',
  ventiladorCon3: '',
  ventilador1: '',
  ventilador2: '',
  ventilador3: '',
  amperaje1: '',
  amperaje2: '',
  amperaje3: '',
  altaInicial: '',
  altaFinal: '',
  bajaInicial: '',
  bajaFinal: '',
  Voltaje1: '',
  Voltaje2: '',
  Voltaje3: '',
  temperatura: '',
  manoMarca: '',
  manoModelo: '',
  manoSerie: '',
  pinzaMarca: '',
  pinzaModelo: '',
  pinzaSerie: '',
  termoMarca: '',
  termoModelo: '',
  termoSerie: '',
};

export default (state = initialState, {type, payload}) => {
  switch (type) {
    case CLEAR_STATE_USER:
      return {
        ...state,
        user: {},
        token: '',
      };
    case CLEAR_DATA_REPORT:
      return {
        ...state,
        codSofya: '',
        idClienteSelect: 0,
        direccion: '',
        idSupervisorSelect: 0,
        ubicacion: '',
        fecha: '',
        horInicio: '00:00',
        horFin: '00:00',
        idMarcaAir: 0,
        idTipoAir: 0,
        capacidadAir: '',
        energiaAir: '',
        refrigeranteAir: '',
        idMarcaVen: 0,
        idTipoVen: 0,
        capacidadVen: '',
        energiaVen: '',
        idEquipoGen: 0,
        modeloGen: '',
        serieGen: '',
        idEquipoTwoGen: 0,
        modeloTwoGen: '',
        serieTwoGen: '',
        observaciones: '',
        recomendaciones: '',
        compresor1: '',
        compresor2: '',
        compresor3: '',
        ventiladorCon1: '',
        ventiladorCon2: '',
        ventiladorCon3: '',
        ventilador1: '',
        ventilador2: '',
        ventilador3: '',
        amperaje1: '',
        amperaje2: '',
        amperaje3: '',
        altaInicial: '',
        altaFinal: '',
        bajaInicial: '',
        bajaFinal: '',
        Voltaje1: '',
        Voltaje2: '',
        Voltaje3: '',
        temperatura: '',
        manoMarca: '',
        manoModelo: '',
        manoSerie: '',
        pinzaMarca: '',
        pinzaModelo: '',
        pinzaSerie: '',
        termoMarca: '',
        termoModelo: '',
        termoSerie: '',
      };
    case SET_INITIAL_DATA:
      return {
        ...state,
        clients: payload.clients,
        brandsCon: payload.brandsCon,
        brandsAir: payload.brandsAir,
        equipCon: payload.equipCon,
        equipAir: payload.equipAir,
        supervisors: payload.supervisors,
        accesories: payload.accesories,
      };
    case SET_INPUT_USER:
      const {prop, value} = payload;
      return {
        ...state,
        [prop]: value,
      };
    case WAITING_DATA:
      return {
        ...state,
        loading: true,
      };
    case STOP_WAITING_DATA:
      return {
        ...state,
        loading: false,
      };
    default:
      return state;
  }
};
