export const CLEAR_STATE_USER = 'CLEAR_STATE_USER';
export const SET_INPUT_USER = 'SET_INPUT_USER';
export const WAITING_DATA = 'WAITING_DATA';
export const STOP_WAITING_DATA = 'STOP_WAITING_DATA';
export const SET_INITIAL_DATA = 'SET_INITIAL_DATA';
export const CLEAR_DATA_REPORT = 'CLEAR_DATA_REPORT';
